# Generated by Django 5.2.8 on 2025-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='locale',
        ),
        migrations.AlterField(
            model_name='user',
            name='voice_preference',
            field=models.CharField(choices=[('idera', 'Idera - Melodic, gentle'), ('emma', 'Emma - Authoritative, deep'), ('zainab', 'Zainab - Soothing, gentle'), ('osagie', 'Osagie - Smooth, calm'), ('wura', 'Wura - Young, sweet'), ('jude', 'Jude - Warm, confident'), ('chinenye', 'Chinenye - Engaging, warm'), ('tayo', 'Tayo - Upbeat, energetic'), ('regina', 'Regina - Mature, warm'), ('femi', 'Femi - Rich, reassuring'), ('adaora', 'Adaora - Warm, engaging'), ('umar', 'Umar - Calm, smooth'), ('mary', 'Mary - Energetic, youthful'), ('nonso', 'Nonso - Bold, resonant'), ('remi', 'Remi - Melodious, warm'), ('adam', 'Adam - Deep, clear')], default='tayo', max_length=50),
        ),
    ]
