# Generated by Django 5.2.8 on 2025-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companion", "0004_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
