# Generated by Django 5.2.8 on 2025-11-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companion", "0005_message_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="voice_preference",
            field=models.CharField(
                choices=[
                    ("Idera", "Idera - Melodic, gentle"),
                    ("Emma", "Emma - Authoritative, deep"),
                    ("Zainab", "Zainab - Soothing, gentle"),
                    ("Osagie", "Osagie - Smooth, calm"),
                    ("Wura", "Wura - Young, sweet"),
                    ("Jude", "Jude - Warm, confident"),
                    ("Chinenye", "Chinenye - Engaging, warm"),
                    ("Tayo", "Tayo - Upbeat, energetic"),
                    ("Regina", "Regina - Mature, warm"),
                    ("Femi", "Femi - Rich, reassuring"),
                    ("Adaora", "Adaora - Warm, engaging"),
                    ("Umar", "Umar - Calm, smooth"),
                    ("Mary", "Mary - Energetic, youthful"),
                    ("Nonso", "Nonso - Bold, resonant"),
                    ("Remi", "Remi - Melodious, warm"),
                    ("Adam", "Adam - Deep, clear"),
                ],
                default="Chinenye",
                max_length=50,
            ),
        ),
    ]
